/* Execute esse script para resetar todos os objetos do Oracle Live SQL */

DROP TABLE TB_REALIZA;
DROP TABLE TB_MULTA;
DROP TABLE TB_HOSPEDE;
DROP TABLE TB_FAZER_MANUTENCAO;
DROP TABLE TB_PAGAMENTO;
DROP TABLE TB_FUNCIONARIO;
DROP TABLE TB_RESERVA;
DROP TABLE TB_QUARTO;
DROP TABLE TB_TIPO_QUARTO;
DROP TABLE TB_PESSOA;
DROP TABLE DEPENDENTE_NT;
DROP TABLE TB_CARGO;

DROP TYPE TP_REALIZA;
DROP TYPE TP_MULTA;
DROP TYPE TP_HOSPEDE;
DROP TYPE TP_FAZER_MANUTENCAO;
DROP TYPE TP_PAGAMENTO;
DROP TYPE TP_FUNCIONARIO;
DROP TYPE TP_RESERVA;
DROP TYPE TP_QUARTO;
DROP TYPE TP_TIPO_QUARTO;
DROP TYPE TP_PESSOA;
DROP TYPE TP_NT_DEPENDENTE;
DROP TYPE TP_DEPENDENTE;
DROP TYPE TP_TELEFONE;
DROP TYPE TP_CARGO;
DROP TYPE NT_TELEFONE;
DROP TYPE TP_TELEFONE_NT;

DROP SEQUENCE SEQ_MULTA;
DROP SEQUENCE SEQ_PAGAMENTO;

DROP TRIGGER TRG_MULTA;
DROP TRIGGER TRG_PAGAMENTO;
